### ISSUE TITLE
png compression not working via backend

### ISSUE THREAD

**Issue by majomap** [shopware5/shopware#2563]
### Description

I just uploaded png files via backend and configured the album to create thumbnails of the uploaded png images.
I set the configuration of the thumbnail quality to 90 and generated the thumbnails.
After I noticed the file size of the generated thumbnails, I changed the quality to 30 and generated the thumbnails again.
But the change didn´t had any effect to the file size of the generated thumbnails.

### PHP Version

7.4

### Shopware Version

5.7.18

### How to reproduce

See descirption.

### Expected behaviour

The file size of the generated thumbnails should be minimized when lowering the quality.

### Actual behaviour

See description.

**Comment by aragon999** [comment]
Have you made sure that you have at least one optimizer installed, which can compress png files?

Run `php bin/console sw:media:optimize --info` to verify this. 
Or check the "Settings -> Systeminfo > Media Optimzer" backend overview.

**Comment by majomap** [comment]
+-----------+----------+-----------------------+
| Optimizer | Runnable | Supported mime-types  |
+-----------+----------+-----------------------+
| jpegoptim | Yes      | image/jpeg, image/jpg |
| pngout    | Yes      | image/png             |
| jpegtran  | Yes      | image/jpeg, image/jpg |
| optipng   | Yes      | image/png             |
| pngcrush  | Yes      | image/png             |
| guetzli   | Yes      | image/jpeg, image/jpg |
+-----------+----------+-----------------------+

**Comment by mitelg** [comment]
hey @majomap 

did that misbehaviour only occurred in 5.7.18 or do you have this issue also in older versions?

**Comment by majomap** [comment]
hi @mitelg,

this misbehaviour was proofed by shopware support employee for the version 5.7.18.
We won´t downgrade our version or install an older version to find this out.
But I would say it occured in older versions, because images has been loading slowy before version 5.7.18.

**Comment by mitelg** [comment]
hey @majomap 

we will evaluate again, if the issue was introduced with 5.7.18 or not. If the issue was already there in older versions, we are not going to fix that, as we are already in the end-of-life phase of Shopware 5 where we only provide fixes for security problems.

**Comment by mitelg** [comment]
hey @majomap 

I just want to inform you, that we are going to have a look at this issue.

**Comment by mitelg** [comment]
hey @majomap 

Finally I had the time to investigate this issue further. I think, there is a misunderstanding on how thumbnail generation and the CLI command `sw:media:optimize` have to be used. 

As you can see in the [thumbnail generator](https://github.com/shopware5/shopware/blob/v5.7.18/engine/Shopware/Components/Thumbnail/Generator/Basic.php#L269-L271) the "quality" setting of the album is not considered for PNG images, but only for JPEGs. It is like this, since a refactoring of the thumbnail generator somewhere in version 4.3.x (and probably also before that, so basically since ever). So there is no wrong behaviour in generating thumbnails for PNG images at all. 

On the other hand the `sw:media:optimize` command can change the sizes of your images, and this also for PNGs. This does not happen, while triggering the generation of the thumbnails, but runs automatically during the upload of an image or has to be executed manually. More information about that can be found here: https://docs.shopware.com/en/shopware-5-en/content-and-media/media#shopware-media-optimizer

Hope this clarifies the things a bit. If not, feel free to add another comment here. 

Best regards from Schöppingen
Michael Telgmann
