### ISSUE TITLE
Commandline importing/updating

### ISSUE THREAD

**Issue by terwey** [shopware5/shopware#54]
Hi,

it would be very nice to have a commandline interface for updating and importing articles/images into Shopware.
For example I am now running an import of product images into Shopware from my browser. This however is of course going to take a while and the chances that it might halfway quit because of a timeout/ip change is realistic.
If I could just through SSH do something like:
`./tools/import.php --images somefile.csv &`

It would just happily run in the background (implied by the &) or just run along in an detached `screen` session through the night :)

Symfony2 has an extremely nice CLI Component ( http://symfony.com/doc/master/components/console/index.html ) designed for creating things like these. But before I spend a few hours on coding this for Shopware while there is already something on the way I wanted to ask here first.

**Comment by terwey** [comment]
As expected, the importing of images has failed me now already 4x. I will start today probably on a basic commandline import tool. I hope anyway I can just call upon the existing import mechanism vs. figuring out how it works ;)

Ok, I just found: https://github.com/ShopwareAG/Shopware4-CLI-Tools
Didn't know that was a seperate project. It doesn't seem to support importing/updating yet but I'll look at that project first :)

**Comment by dnoegel** [comment]
Hi Terwey, currently the import interface has problems with huge amounts of data, especially when copying thousands of images. I think  a possible solution might  be to split the csv on the server and to import it in multiple, small requests. Right now you might have to split your CSV on your own and check, if you can import smaller chunks. 

Due to this considerations, I think we'd rather improve the existing interface before adding an additional one to our CLI

**Comment by terwey** [comment]
Hi @dnoegel,

you should -never- add an additional one to the CLI. You should then expose the existing one to the CLI. Else your maintaining two code bases which is a lot of work and also unnecessary.

I however -always- prefer a CLI tool for importing/exporting information because it's usually more stable (and it doesn't run in a flimsy browser).

btw: is there an IRC channel for Shopware? Last year on the Shopware Forums I asked but nobody responded to it :(

**Comment by dnoegel** [comment]
Hi terwey,

there is no IRC channel for shopware, yet. Regarding the CLI tool: Of course no one wants to add an all new interface to the CLI tool instead of using the old one. :) What I wanted to say: Right now there are no plans to extend the CLI tool in such a way and I think we'd rather spent the effort on the existing ImportExport interface.

However, feel free to fork our CLI and create such an extension. I guess that there a some people out there, who would like to use such a tool

**Comment by terwey** [comment]
@dnoegel,

After I'm done playing with the new setup I'll take a look at implementing the import tool into the CLI environment cause I'm -quite- sure I will need to do that again ;)

Concerning IRC, I would -really- recommend something like #shopware on irc.freenode.net as it's an OSS project nowadays and a simple back and forth question like this would've been a lot easier :)
Also in my opinion an IRC channel adds community feeling... but maybe I'm just an IRC zealot ;)

**Comment by soerenmartius** [comment]
@terwey

Did you started an additional fork for the import topic? I thought about starting a little project for command based imports combined with an web interface for category mapping and all the other stuff we need for our dropshipping shops. I highly recommend you to use the master branch of smfony2's cli component cause there are massiv changes with the upcoming 2.2.

If you are interested to talk this issue dont hesitate to add me in skype: aicarambaa

+1 for the #shopware channel on freenode

**Comment by dnoegel** [comment]
Hi, 

I'll close this issue as we are currently not planing to implement a CLI importer. Our all new official #shopware channel can be found on freenode.net :)
