### ISSUE TITLE
have_innodb doesn't exist in MySQL 5.6. any more

### ISSUE THREAD

**Issue by zavalit** [shopware5/shopware#78]
A check for MySQL Variable "have_innodb"  returns in Shopware_Install_Database.php simply nothing. That makes an istall of shopware-4 impossible, at least with MySQL 5.6

**Comment by bcremer** [comment]
Hi @zavalit,

we just fixed this bug two days ago.
See this commit:
https://github.com/ShopwareAG/shopware-4/commit/ea72bacc51be39f9608c1ded050ee8f14f73c43f

We now parse 'SHOW ENGINES;' instead of the deprecated 'have_innodb'-Variable.

I think this will fix your problem.
Just replace the affected file in the RC-Package with the current file from our next-branch.
